### ISSUE TITLE
Roadmap change

### ISSUE THREAD

**Issue by MaloRchrd** [MaloRchrd/first-map#1]
Hello @thaume, 

Bon, j'ai réfléchis et je pense que c'est encore un peu tôt pour moi pour me lancer dans l'app direct.

j'ai surtout  trouvé une étape intéressante, qui me parait plus accessible. En gros je veux faire un petit messenger bot qui te demande ta géoloc et renvoie un lien avec la latitude et longitude en paramètres qui charge la page sur ta position.   

Je n'ai pas réussi a trouver dans la doc de Mapbox ni dans des modules complémentaire. 

Du coup mon plan d'attaque : 

-Essayer de recevoir les paramètres (lat et long) de url en javascript.les stocker (je ne sais pas encore comment) et les renvoyer dans cette fonction de mapbox  
 `map.setCenter([lat, long]);` 

J'ai trouvé ça 

Return the querystring part of a URL. Assume that the current URL is `http://www.w3schools.com/submit.htm?email=someone@example.com:
`
`var x = location.search;
`The result of x will be:

`?email=someone@example.com`

Penses-tu que c'est la bonne démarche ? 
Y'a t'il plus facile ? 

Pour la partie bot, je pense pouvoir me débrouiller pour créer le bot, demander la géoloc, recevoir les info et générer `l'url` avec la `lat` et `long` en paramètres. 

Dsl c'est un peu long 
Encore merci 👍

**Comment by MaloRchrd** [comment]
J'ai réussi la première partie :-)

<img width="1083" alt="capture d ecran 2016-10-19 a 20 03 18" src="https://cloud.githubusercontent.com/assets/17042850/19531219/2a617198-9637-11e6-9afb-281a5b7d4f79.png">

Suite a ça je me suis dis que je pouvais créer mon `url scheme` comme ça : 

```
www.exemple.com?lat, long 
www.exemple.com?48.862,2.287
```

Du coup j'ai viré le ? et envoyé le résultat dans ma fonction direct 

comme ca 

```
var param = location.search;
alert (param);
var result = param.slice(1, -1);
alert (result);
map.setCenter(result);
```

[https://github.com/MaloRchrd/first-map/blob/master/Index.html#L97](https://github.com/MaloRchrd/first-map/blob/master/Index.html#L97)

Mais ça ne marche pas 

La fonction est comme ça dans la doc 

[https://www.mapbox.com/help/set-map-position/#mapbox-gl-js](https://www.mapbox.com/help/set-map-position/#mapbox-gl-js)

[EDIT] Je comprend pas 

Quand je met le code en dure comme ça `map.setCenter([0.199556000,48.00611000]);` ça fonctionne bien ma map ce charge au bon endroit. 
et quand j'utilise ma variable `map.setCenter([result]);`
 et mon `alerte(result)` donne bien 0.199556000,48.00611000
Mais la carte ne se charge pas. 

Du coup j'ai plus trop d'idée a part peut être le format de ma variable ( objet ? string ?) 
Mais Mapbox me dis rien sur le format qu'il doit recevoir et c'est un chapitre ou j'ai pas tout compris.

**Comment by MaloRchrd** [comment]
[Update du lundi ] @thaume

C'est bon j'ai réussi ça aura pris du temps mais ça fonctionne.  Il faut juste que je rajoute une condition si il n'y a rien d'attribué au valeur lat et lon  mettre une valeur par défaut

**Comment by thaume** [comment]
👍🏿
